apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gtplus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: gtplus
    repoURL: 'https://github.com/yunjoo11/gtplus.git'
    targetRevision: test
  project: gtplus
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
