apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yunjoo95/gtplus:20250402231836_6
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: myapp-cm
